# Generated by Django 4.0.6 on 2022-07-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemoncard_api', '0002_pokemoncard_pokedexindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemonType', models.CharField(max_length=30)),
            ],
        ),
    ]
