# Generated by Django 4.0.6 on 2022-07-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemoncard_api', '0003_pokemontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('productionstart', models.DateField()),
                ('productionend', models.DateField()),
                ('icon', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='pokemontype',
            name='pokemonType',
            field=models.CharField(max_length=2048),
        ),
    ]
