# Generated by Django 4.0.6 on 2022-07-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemoncard_api', '0004_pokemoncardset_alter_pokemontype_pokemontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoncardset',
            name='icon',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='pokemontype',
            name='pokemonType',
            field=models.CharField(max_length=30),
        ),
    ]
