# Generated by Django 4.0.6 on 2022-08-05 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemoncard_api', '0007_pokemoncard_pokemoncardset'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemoncard',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pokemoncard_api.pokemontype'),
        ),
    ]
