# Generated by Django 4.0.6 on 2022-08-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemoncard_api', '0008_pokemoncard_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemoncard',
            name='pokemonType',
        ),
    ]
