# Generated by Django 4.0.6 on 2022-08-09 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemoncard_api', '0009_remove_pokemoncard_pokemontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('collectedCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemoncard_api.pokemoncard')),
            ],
        ),
    ]
