# Generated by Django 4.0.6 on 2022-08-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemoncard_api', '0010_pokemoncollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoncollection',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
