# Generated by Django 4.0.6 on 2022-09-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemoncard_api', '0013_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loggedIn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.CharField(default='https://www.kindpng.com/picc/m/121-1210821_cat-face-cute-cat-face-clipart-hd-png.png', max_length=2048),
        ),
    ]
