# Generated by Django 4.0.6 on 2022-09-19 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemoncard_api', '0014_user_loggedin_alter_user_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoncollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemoncard_api.user'),
        ),
    ]
